
IF OBJECT_ID('PLAYERS') IS NOT NULL
DROP TABLE PLAYERS;

IF OBJECT_ID('TEAMS') IS NOT NULL
DROP TABLE TEAMS;

CREATE TABLE PLAYERS (
    PLAYER_ID INT,
    PLAYER_NAME NVARCHAR(255),
    AGE INT,
    INJURY BIT,
    PRIMARY KEY (PLAYER_ID)

)

CREATE TABLE TEAMS (
    LEAGUE_ID INT,
    LEAGUE_NAME NVARCHAR(255),
    PLAYER_ID INT
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (PLAYER_ID)
)


INSERT INTO PLAYERS(PLAYER_ID,PLAYER_NAME,AGE,INJURY)
VALUES(1, 'JOHNNY BOY', 29, 0),
(2, 'TOHNNY BOY', 31, 1),
(3, 'DOHNNY BOY', 35, 0)

INSERT INTO TEAMS(LEAGUE_ID,LEAGUE_NAME, PLAYER_ID)
VALUES (1, 'FFS LEAGUE', 1), 
(1, 'FFS LEAGUE', 3)

SELECT * FROM Teams


