
IF OBJECT_ID('PLAYERS') IS NOT NULL
DROP TABLE PLAYERS;

IF OBJECT_ID('TEAMS') IS NOT NULL
DROP TABLE TEAMS;

CREATE TABLE PLAYERS (
    PLAYER_ID INT (1,1),
    PLAYER_NAME NVARCHAR(255),
    AGE INT,
    INJURY BOOLEAN,
    PRIMARY KEY (PLAYER_ID)

)

CREATE TABLE TEAMS (
    LEAGUE_ID INT (1,1),
    LEAGUE_NAME NVARCHAR(255),
    PLAYER_ID INT
    PRIMARY KEY (LEAGUE_ID)
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (PLAYER_ID)
)